# Generated by Django 3.1.3 on 2020-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('engine_size', models.IntegerField()),
                ('body_type', models.CharField(choices=[('custom cruiser', 'Custom Cruiser'), ('super sports', 'Super Sports'), ('naked', 'Naked'), ('tourer', 'Tourer'), ('adventure', 'Adventure')], max_length=14)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='bike_store')),
                ('is_used', models.BooleanField()),
            ],
        ),
    ]
