# Generated by Django 3.1.3 on 2020-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_store', '0002_auto_20201206_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='name',
        ),
        migrations.AddField(
            model_name='bike',
            name='make',
            field=models.CharField(choices=[('APRILIA', 'APRILIA'), ('BENELLI', 'BENELLI'), ('BMW', 'BMW'), ('DUCATI', 'DUCATI'), ('FIAT', 'FIAT'), ('HANWAY', 'HANWAY'), ('HARLEY-DAVIDSON', 'HARLEY-DAVIDSON'), ('HONDA', 'HONDA'), ('HYOSUNG', 'HYOSUNG'), ('KAWASAKI', 'KAWASAKI'), ('KEEWAY', 'KEEWAY'), ('KTM', 'KTM'), ('LEXMOTO', 'LEXMOTO'), ('MONDIAL', 'MONDIAL'), ('MOTO GUZZI', 'MOTO GUZZI'), ('PIAGGIO', 'PIAGGIO'), ('ROYAL ENFIELD', 'ROYAL ENFIELD'), ('SUZUKI', 'SUZUKI'), ('TRIUMPH', 'TRIUMPH'), ('YAMAHA', 'YAMAHA')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
